ktor:
  deployment:
    port: 8080
  application:
    modules:
      - io.github.iamnicknack.pjs.http.server.ApplicationKt.koinModule
      - io.github.iamnicknack.pjs.http.server.ApplicationKt.module
  development: false
